In [1]:
import pandas as pd

workdir = 'C:\\Users\\ed.deane\\Python\\AdventOfCode\\Day 9 Rope Bridge\\'

df= pd.read_csv(workdir+'input.txt', sep=' ',header=None)

In [2]:
#Set up visited_positions_df that will contain all the positions visited by the tail
#x is the column (horizontally) and y is your index, value is the number of occurences
#Create function that will get the existing value for the x,y combination
# create it with value 1 if it doesn't, increment it if already there

# Creates pandas DataFrame.
visited_positions_df = pd.DataFrame({0:1}, index=[0])

In [3]:
def add_position(visited_positions_df,x,y):
    try:
        #Increment the value already at that position
        visited_positions_df.at[y,x] = visited_positions_df.fillna(0)._get_value(y,x, takeable=False)+1
    except KeyError:
        visited_positions_df.at[y,x] = 1
    
    return visited_positions_df

In [4]:
H=(0,0)
T=(0,0)
def move(knot,move):
    if(move[0]=='R'):
        knot=(knot[0]+int(move[1]),knot[1])
    if(move[0]=='L'):
        knot=(knot[0]-int(move[1]),knot[1])
    if(move[0]=='U'):
        knot=(knot[0]),knot[1]+int(move[1])
    if(move[0]=='D'):
        knot=(knot[0]),knot[1]-int(move[1])
    return knot

# If the tail is more than a step away, move it closer relative to the Head

def move_tail(T,H):
    change = True
    #if head and tail are within a square then do nothing
    if(abs(T[0] - H[0]) < 2 and abs(T[1] - H[1]) < 2):
        T=T
        change = False
    #where the two share a common axis, then move tail towards head
    elif (T[0] - H[0]) == 0:
        step = (H[1]-T[1])/abs(H[1]-T[1])
        T=(T[0],int(T[1]+step))
    elif (T[1] - H[1]) == 0:
        step = (H[0]-T[0])/abs(H[0]-T[0])
        T=(int(T[0]+step),T[1])
        
    else:
        stepx = (H[0]-T[0])/abs(H[0]-T[0])
        stepy = (H[1]-T[1])/abs(H[1]-T[1])
        T=(int(T[0]+stepx),int(T[1]+stepy))
    #finally if both the axis are different then bring it in diagonally

    return T,change

# For each move in the file
for index, row in df.iterrows():
    #print(row[0], row[1])
    
    # Move the Head one at a time based on the move
    for i in range(row[1]):
        H=move(H,(row[0],1))
        T,change=move_tail(T,H)
        if (change):
            #record visited position
            visited_positions_df = add_position(visited_positions_df,T[0],T[1])   
        # For each step in the move, ensure the Tail is at most on step away
        #print ('Head',H,'Tail',T)
visited_positions_df

,0,1,2,3,4,5,6,7,8,9,...,-137,-138,-139,-140,-141,-142,-143,-144,-145,-146
0,5.0,6.0,5.0,3.0,2.0,2.0,4.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-1,6.0,2.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-2,4.0,2.0,NaN,1.0,1.0,NaN,2.0,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-3,1.0,1.0,1.0,1.0,2.0,1.0,3.0,2.0,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-4,1.0,NaN,1.0,NaN,2.0,3.0,4.0,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print("Non NaN values:\n",visited_positions_df.count().sum())

Non NaN values:
 6243